[package]
authors = ["Steven Sloboda <ssloboda@starry.com>"]
name = "bonusly-bot"
version = "0.1.0"

[dependencies]
clap = "2.26"
error-chain = "0.11"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
tokio-core = "0.1"
